# file_types.py
#
# Copyright 2025 koxt2
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#
# SPDX-License-Identifier: GPL-2.0-or-later

# Groups for organizing categories in the UI
FILE_TYPE_GROUPS = {
    "Documents &amp; Office": [
        "Documents",
        "Spreadsheets",
        "Publishing",
        "Office Documents (ZIP-based)",
        "eBooks",
    ],
    "Media": [
        "Images",
        "Audio &amp; Music",
        "Video",
    ],
    "Design &amp; Graphics": [
        "Design &amp; CAD",
        "Graphics &amp; Photography",
        "Fonts",
    ],
    "Development &amp; Data": [
        "Code &amp; Development",
        "Database",
        "Web &amp; Internet",
    ],
    "Archives &amp; Backups": [
        "Archive",
        "Disk Images &amp; Backup",
    ],
    "Professional": [
        "Finance &amp; Accounting",
        "Email &amp; Contacts",
        "Scientific &amp; Medical",
    ],
    "System &amp; Other": [
        "System &amp; Config",
        "Encryption &amp; Security",
        "Gaming",
        "Others",
    ],
}

FILE_TYPES = {
    "Documents": {
        "chm": ["chm"],
        "djv": ["djv"],
        "doc": ["doc", "ppt", "xls", "msg", "pub", "rtf", "sda", "sdc", "sdd", "sdw"],
        "dvi": ["dvi"],
        "one": ["one"],
        "pdf": ["pdf"],
        "txt": ["txt", "adr", "csv", "cue", "dif", "emlx", "fb2", "ics", "ldif", "ly", "lyx", "m3u", "mem", "priv", "pts", "ram", "slk", "smil", "stp", "tex", "ttd", "vcf", "wpl", "xmp"],
        "wpd": ["wpd"],
    },
    "Spreadsheets": {
        "doc": ["xlr", "wps", "et", "fods"],
        "wks": ["wk4", "wks"],
    },
    "Images": {
        "bmp": ["bmp"],
        "bpg": ["bpg"],
        "crw": ["crw"],
        "gif": ["gif"],
        "icns": ["icns"],
        "ico": ["ico"],
        "jpg": ["jpg", "mpo"],
        "mov": ["cr3", "heic", "jp2"],
        "mrw": ["mrw"],
        "orf": ["orf"],
        "pct": ["pct"],
        "pcx": ["pcx"],
        "png": ["jng", "mng", "png"],
        "pnm": ["pbm", "pgm", "pnm", "ppm"],
        "raf": ["raf"],
        "raw": ["raw"],
        "riff": ["webp"],
        "rw2": ["rw2"],
        "tiff": ["arw", "cr2", "dcr", "dng", "nef", "pef", "sr2", "tif"],
        "wdp": ["wdp"],
        "x3f": ["x3f"],
    },
    "Audio &amp; Music": {
        "aif": ["aif", "iff"],
        "als": ["als"],
        "ape": ["ape"],
        "au": ["au"],
        "caf": ["caf"],
        "flac": ["flac"],
        "flp": ["flp"],
        "gp2": ["gp2"],
        "gp5": ["gp4", "gp5", "gpx"],
        "gsm": ["gsm"],
        "it": ["it"],
        "logic": ["logic"],
        "mid": ["mid"],
        "mp3": ["mp3"],
        "mus": ["mus"],
        "ogg": ["ogg", "ogm", "ogv"],
        "ptb": ["ptb"],
        "ra": ["ra"],
        "riff": ["cda", "qcp", "wav"],
        "rns": ["rns"],
        "rx2": ["rx2"],
        "ses": ["ses"],
        "shn": ["shn"],
        "sib": ["sib"],
        "wv": ["wv"],
        "xm": ["xm"],
        "zip": ["xrns"],
    },
    "Video": {
        "tivo": ["TiVo"],
        "asf": ["asf", "wma", "wmv"],
        "dv": ["dv"],
        "dvr": ["dvr"],
        "fcp": ["fcp"],
        "flv": ["flv"],
        "m2ts": ["m2t", "m2ts", "tod", "ts"],
        "mkv": ["mkv", "webm"],
        "mlv": ["mlv"],
        "mov": ["3g2", "3gp", "m4p", "mov", "mp4"],
        "mpg": ["mpg"],
        "mxf": ["mxf"],
        "r3d": ["r3d"],
        "rm": ["rm"],
        "tiff": ["avi"],
        "veg": ["veg"],
        "wtv": ["wtv"],
    },
    "Archive": {
        "7z": ["7z"],
        "a": ["a", "deb"],
        "ace": ["ace"],
        "arj": ["arj"],
        "bz2": ["bz2"],
        "cab": ["cab"],
        "dar": ["dar"],
        "dump": ["dump"],
        "gz": ["gz", "html.gz", "pvp", "tar.gz", "xml.gz", "xoj"],
        "lzh": ["lzh"],
        "lzo": ["lzo"],
        "par2": ["par2"],
        "rar": ["rar"],
        "rpm": ["rpm"],
        "sit": ["sit"],
        "tar": ["tar"],
        "wim": ["wim"],
        "xar": ["xar"],
        "xz": ["xz"],
        "zip": ["zip"],
    },
    "Design &amp; CAD": {
        "3dm": ["3dm"],
        "binvox": ["binvox"],
        "bld": ["bld", "blend"],
        "c4d": ["c4d"],
        "catdrawing": ["CATDrawing"],
        "doc": ["3ds", "dgn", "ipt", "rvt", "sld", "sldprt", "vsd", "camrec"],
        "drw": ["drw"],
        "dwg": ["dwg"],
        "dxf": ["dxf"],
        "emf": ["emf"],
        "lxo": ["lwo", "lxo"],
        "max": ["max"],
        "mb": ["mb", "mp"],
        "prt": ["prt"],
        "skp": ["skp"],
        "stl": ["stl"],
        "wmf": ["wmf"],
        "zip": ["sh3d", "sketch", "vsdx", "xd"],
    },
    "Graphics &amp; Photography": {
        "abr": ["abr"],
        "acb": ["acb"],
        "ado": ["ado"],
        "afdesign": ["afdesign"],
        "asl": ["asl"],
        "cdt": ["cdd", "cdl", "cdt"],
        "csh": ["csh"],
        "doc": ["fla", "psmodel"],
        "dpx": ["dpx"],
        "fh10": ["fh1", "fh10"],
        "fh5": ["fh5"],
        "pdf": ["ai"],
        "psb": ["psb"],
        "psd": ["psd"],
        "riff": ["cdr"],
        "xcf": ["xcf"],
        "zip": ["kra", "ora"],
    },
    "Database": {
        "berkeley": ["db"],
        "dbf": ["dbf"],
        "doc": ["db", "wdb"],
        "edb": ["edb"],
        "fdb": ["fdb"],
        "fp5": ["fp5"],
        "fp7": ["fp7", "fp12"],
        "ibd": ["ibd"],
        "ldf": ["ldf"],
        "mdb": ["accdb", "mdb"],
        "mysql": ["MYI"],
        "sql": ["sqlite"],
        "txt": ["sql"],
    },
    "Email &amp; Contacts": {
        "nk2": ["nk2"],
        "pst": ["dbx", "pst", "wab"],
    },
    "Finance &amp; Accounting": {
        "gz": ["gnucash", "kmy"],
        "mdb": ["mny"],
        "myo": ["myo"],
        "qbb": ["qbb", "qbmb", "qbw"],
        "qdf": ["qdf", "qdf-backup"],
        "steuer2014": ["steuer2014", "steuer2015"],
        "tax": ["tax"],
    },
    "Code &amp; Development": {
        "asm": ["asm"],
        "class": ["class"],
        "dex": ["dex"],
        "elf": ["elf"],
        "exe": ["dll", "exe"],
        "jks": ["jks"],
        "jsonlz4": ["jsonlz4", "json"],
        "pyc": ["pyc"],
        "txt": ["bat", "c", "cls", "f", "h", "jad", "pl", "pli", "pm", "ppk", "py", "rb", "rsa", "sh", "vb"],
        "zip": ["apk", "jar", "xpi"],
    },
    "Publishing": {
        "cwk": ["cwk"],
        "doc": ["p65", "qpw", "tcw"],
        "indd": ["ind", "indd"],
        "pap": ["pap"],
        "ps": ["eps", "ps"],
        "qxd": ["qxd", "qxp"],
        "txt": ["sla"],
    },
    "eBooks": {
        "lit": ["lit"],
        "mobi": ["mobi"],
        "pdb": ["pdb"],
        "zip": ["epub"],
    },
    "Disk Images &amp; Backup": {
        "bkf": ["bkf"],
        "cow": ["cow"],
        "dim": ["dim", "diskimage"],
        "e01": ["e01"],
        "fbf": ["fbf"],
        "fbk": ["fbk"],
        "gho": ["gho"],
        "gi": ["gi"],
        "iso": ["iso"],
        "filevault": ["img", "sparseimage"],
        "msa": ["msa"],
        "tib": ["tib"],
        "v2i": ["v2i"],
        "vdi": ["vdi"],
        "vmdk": ["vmdk"],
    },
    "Gaming": {
        "d2s": ["d2s"],
        "gam": ["gam"],
        "gm6": ["gm6", "gm81", "gmd", "gmk"],
        "gz": ["schematic"],
        "nds": ["nds"],
        "nes": ["nes"],
        "save": ["save"],
    },
    "Scientific &amp; Medical": {
        "dcm": ["dcm"],
        "dta": ["dta"],
        "fcs": ["fcs"],
        "fit": ["fit"],
        "fits": ["fits"],
        "gz": ["bai", "bam", "bgz", "csi", "RData"],
        "hdf": ["hdf"],
        "mat": ["mat"],
        "nd2": ["nd2"],
        "pds": ["pds"],
        "spss": ["sav", "spss"],
    },
    "System &amp; Config": {
        "dat": ["dat"],
        "ds_store": ["ds_store"],
        "evt": ["evt"],
        "evtx": ["evtx"],
        "lnk": ["lnk"],
        "pf": ["pf"],
        "reg": ["reg"],
        "txt": ["inf", "ini", "plist"],
    },
    "Encryption &amp; Security": {
        "axx": ["axx"],
        "ecryptfs": ["ecr", "eCryptfs"],
        "gpg": ["gpg", "pgp"],
        "kdb": ["kdb"],
        "kdbx": ["kdbx"],
        "luks": ["luks"],
        "pfx": ["pfx"],
        "vault": ["vault"],
        "wallet": ["wallet"],
    },
    "Web &amp; Internet": {
        "http": ["http"],
        "swf": ["swc", "swf"],
        "torrent": ["torrent"],
        "txt": ["asp", "html", "jsp", "php", "svg", "url", "xml"],
    },
    "Fonts": {
        "ttf": ["ttf"],
        "woff": ["woff"],
        "vfb": ["vfb"],
    },
    "Office Documents (ZIP-based)": {
        "zip": ["celtx", "docx", "kmz", "mmap", "notebook", "odg", "odp", "ods", "odt", "pages", "pptx", "sxc", "sxd", "sxi", "sxw", "xlsx"],
    },
    "Others": {
        "ahn": ["ahn"],
        "all": ["all"],
        "amd": ["amd", "amt", "atd", "att"],
        "amr": ["amr"],
        "apa": ["apa"],
        "apple": ["apple"],
        "ari": ["ari"],
        "atd": ["atd"],
        "axp": ["axp"],
        "ab": ["ab"],
        "bac": ["bac"],
        "bdm": ["bdm"],
        "bin": ["ticket.bin"],
        "bim": ["bim"],
        "bvr": ["bvr"],
        "cam": ["cam"],
        "che": ["che"],
        "cm": ["cm", "comicdoc"],
        "compress": ["compress", "cp_"],
        "cpi": ["cpi"],
        "ctg": ["ctg"],
        "dad": ["dad"],
        "dbn": ["dbn"],
        "ddf": ["ddf"],
        "dmp": ["dmp"],
        "doc": ["albm", "amb", "apr", "emb", "jnb", "mws", "snt"],
        "ds2": ["ds2"],
        "dsc": ["dsc"],
        "dss": ["dss"],
        "dst": ["dst"],
        "ess": ["ess"],
        "exs": ["exs"],
        "fds": ["fds"],
        "fm": ["fm"],
        "fob": ["fob"],
        "fos": ["fos"],
        "freeway": ["freeway"],
        "frm": ["frm"],
        "fs": ["fs"],
        "fwd": ["fwd"],
        "gct": ["gct"],
        "hds": ["hds"],
        "hm": ["hm"],
        "hr9": ["hr9"],
        "icc": ["icc"],
        "idx": ["idx"],
        "ifo": ["ifo"],
        "imb": ["imb"],
        "info": ["info"],
        "itu": ["itu", "mhbd"],
        "key": ["key"],
        "lso": ["lso"],
        "mcd": ["mcd"],
        "mdf": ["mdf"],
        "mfa": ["mfa"],
        "mfg": ["mfg"],
        "mig": ["mig"],
        "mk5": ["mk5"],
        "mpl": ["mpl"],
        "njx": ["njx"],
        "nsf": ["nsf"],
        "oci": ["oci"],
        "paf": ["paf"],
        "pcap": ["pcap", "pcp"],
        "pcb": ["pcb"],
        "plt": ["plt"],
        "prc": ["prc"],
        "prd": ["prd"],
        "psf": ["psf"],
        "psp": ["psp"],
        "ptf": ["ptf", "ptx"],
        "pzf": ["pzf"],
        "pzh": ["pzh"],
        "qkt": ["qkt"],
        "rdc": ["rdc"],
        "res": ["res"],
        "rfp": ["rfp"],
        "riff": ["aep", "agn", "ani", "cpr", "idf"],
        "rlv": ["rlv"],
        "sgcta": ["sgcta"],
        "skd": ["skd"],
        "snag": ["snag"],
        "sp3": ["sp3"],
        "spe": ["spe"],
        "spf": ["spf"],
        "sqm": ["sqm"],
        "stu": ["stu"],
        "studio": ["studio"],
        "tg": ["tg"],
        "tph": ["tph"],
        "tpl": ["tpl"],
        "txt": ["dc", "dp", "dsa", "emka", "ers", "fst", "gcs", "gsb", "hdr", "imm", "mcf", "mdl", "msf", "prproj", "pub", "qgs", "rpp"],
        "tz": ["tz"],
        "vdj": ["vdj"],
        "vib": ["vib"],
        "vmg": ["vmg"],
        "wee": ["wee"],
        "win": ["win"],
        "wld": ["wld"],
        "wnk": ["wnk"],
        "wpb": ["wpb"],
        "x3i": ["x3i"],
        "x4a": ["x4a", "x4g", "x4p", "x4s"],
        "xfi": ["xfi"],
        "xpt": ["xpt"],
        "xsv": ["xsv"],
        "xv": ["xv"],
        "z2d": ["z2d"],
        "zcode": ["zcode"],
        "zpr": ["zpr"],
    }
}
